export const ROLES = {
  MASTER_ADMIN: "MASTER_ADMIN",
  MANAGER: "MANAGER",
  SUPERVISOR: "SUPERVISOR",
  STAFF: "STAFF",

  SHOP_OWNER: "SHOP_OWNER",
  SHOP_MANAGER: "SHOP_MANAGER",
  SHOP_SUPERVISOR: "SHOP_SUPERVISOR",
  EMPLOYEE: "EMPLOYEE",
} as const;

export type UserRole = (typeof ROLES)[keyof typeof ROLES];

export const MASTER_ROLES: UserRole[] = [
  ROLES.MASTER_ADMIN,
  ROLES.MANAGER,
  ROLES.SUPERVISOR,
  ROLES.STAFF,
];

export const SHOP_ROLES: UserRole[] = [
  ROLES.SHOP_OWNER,
  ROLES.SHOP_MANAGER,
  ROLES.SHOP_SUPERVISOR,
  ROLES.EMPLOYEE,
];